# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-04 23:11
from __future__ import unicode_literals

from django.db import migrations
import swapfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0003_auto_20170204_2308'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('race', 'seat')},
        ),
        migrations.AlterField(
            model_name='result',
            name='finish',
            field=swapfield.fields.SwapIntegerField(blank=True, default=None, null=True, unique_for_fields=['race'], verbose_name='finish'),
        ),
        migrations.AlterField(
            model_name='result',
            name='qualifying',
            field=swapfield.fields.SwapIntegerField(blank=True, default=None, null=True, unique_for_fields=['race'], verbose_name='qualifying'),
        ),

    ]
