# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0003_auto_20160927_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grandprix',
            name='first_held',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
