# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0005_result_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['contender__driver__last_name', 'team'], 'verbose_name': 'Seat', 'verbose_name_plural': 'Seats'},
        ),
        migrations.RemoveField(
            model_name='seat',
            name='current',
        ),
    ]
