# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0006_auto_20170529_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='driver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='driver27.Driver', verbose_name='driver'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='contender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='driver27.Contender', verbose_name='contender'),
        ),
    ]
