# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0007_auto_20170529_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='seasons',
        ),
    ]
