# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0010_seats_contender_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contender',
            name='teams',
        ),
    ]
