# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0013_auto_20161001_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='fastest_lap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='retired',
            field=models.BooleanField(default=False),
        ),
    ]
