# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0013_remove_seat_contender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contender',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='contender',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='contender',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='competitions',
        ),
        migrations.DeleteModel(
            name='Contender',
        ),
    ]
