# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0014_auto_20170529_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='year_of_birth',
            field=models.IntegerField(blank=True, null=True, verbose_name='year of birth'),
        ),
    ]
