# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0015_auto_20161002_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
