# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0016_competition_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='circuit'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='full_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='competition'),
        ),
        migrations.AlterField(
            model_name='grandprix',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='grand prix'),
        ),
        migrations.AlterField(
            model_name='team',
            name='full_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=75, unique=True, verbose_name='team'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('race', 'qualifying'), ('race', 'contender'), ('race', 'finish')]),
        ),
    ]
