# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0017_auto_20161008_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circuit',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='drivercompetition',
            options={'ordering': ['competition__name', 'driver__last_name', 'driver__first_name']},
        ),
        migrations.AlterModelOptions(
            name='grandprix',
            options={'ordering': ['name'], 'verbose_name_plural': 'grands prix'},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['season', 'round']},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['race__season', 'race__round', 'finish', 'qualifying']},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['competition__name', 'year']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='teamseasonrel',
            options={'verbose_name': 'Team Season', 'verbose_name_plural': 'Teams Season'},
        ),
    ]
