# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0018_populate_competition_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='competitions',
        ),
    ]
