# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0018_auto_20161009_1321'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='drivercompetitionteam',
            unique_together=set([('team', 'enrolled')]),
        ),
    ]
