# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0020_result_wildcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivercompetitionteam',
            name='seasons',
            field=models.ManyToManyField(blank=True, default=None, related_name='team_contenders', to='driver27.Season'),
        ),
    ]
