# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0020_team_competitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='from_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='until_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set([('team', 'driver', 'from_year', 'until_year')]),
        ),
    ]
