# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0022_auto_20170602_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='from_year',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='until_year',
        ),
    ]
