# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 17:37
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0023_auto_20170602_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='country'),
        ),
    ]
