# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0026_populate_fastest_race'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='fastest_lap',
        ),
    ]
