# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('full_name', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
