# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandPrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', django_countries.fields.CountryField(blank=True, default=None, max_length=2, null=True)),
                ('first_held', models.IntegerField()),
                ('competitions', models.ManyToManyField(default=None, related_name='grands_prix', to='driver27.Competition')),
                ('default_circuit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_to_grands_prix', to='driver27.Circuit')),
            ],
        ),
    ]
