# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0004_season'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=set([('year', 'competition')]),
        ),
    ]
