# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0005_auto_20160928_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='name',
            field=models.CharField(max_length=30, verbose_name='circuit'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=30, verbose_name='competition'),
        ),
        migrations.AlterField(
            model_name='grandprix',
            name='name',
            field=models.CharField(max_length=30, verbose_name='grand prix'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=75, verbose_name='team'),
        ),
    ]
