# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0006_auto_20160928_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivercompetitionteam',
            old_name='driver_competition',
            new_name='enrolled',
        ),
        migrations.AlterUniqueTogether(
            name='drivercompetitionteam',
            unique_together=set([('enrolled', 'current'), ('team', 'enrolled')]),
        ),
    ]
