# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 13:17
from __future__ import unicode_literals

from django.db import migrations, models

def copy_teams_season_content(apps, schema_editor):
    Season = apps.get_model("driver27", "Season")
    TeamSeason = apps.get_model("driver27", "TeamSeason")
    for season in Season.objects.all():
        for team in season.teams.all():
            TeamSeason.objects.create(season=season, team=team)



class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0007_auto_20160926_1317'),
    ]

    operations = [
        migrations.RunPython(
            copy_teams_season_content,
        ),
    ]
