# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0008_copy_teams_season_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='teams',
        ),
    ]
