# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0009_remove_season_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='teams_aux',
        ),
        migrations.AddField(
            model_name='season',
            name='teams',
            field=models.ManyToManyField(related_name='seasons', through='driver27.TeamSeason', to='driver27.Team'),
        ),
    ]
