# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0010_auto_20160929_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivercompetitionteam',
            options={'ordering': ['enrolled__driver__last_name', 'team']},
        ),
        migrations.AddField(
            model_name='drivercompetitionteam',
            name='seasons',
            field=models.ManyToManyField(blank=True, default=None, to='driver27.Season'),
        ),
    ]
