# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver27', '0012_result'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('race', 'contender')]),
        ),
    ]
